[service]
name = "ssh"
default_ports = [22, 2222]
description = "Secure Shell Protocol"

# No need to send a payload for SSH typically, as the server sends a banner immediately upon connection.
# But if needed, a probe block can define what to send.
[[probe]]
name = "ssh_client_banner"
payload = "SSH-2.0-Zond_1.0\r\n"
protocol = "tcp"

# Match against the SSH banner sent by the server
[[match]]
name = "openssh_match"
pattern = "^SSH-([\\d.]+)-OpenSSH[_]?([\\w.-]+)"
version_group = 2
vendor = "OpenBSD"
product = "OpenSSH"

[[match]]
name = "dropbear_match"
pattern = "^SSH-([\\d.]+)-dropbear_([\\d.]+)"
version_group = 2
vendor = "dropbear"
product = "dropbear"
