# This file contains fingerprints imported from Rapid7 Recog.
# Source: https://github.com/rapid7/recog
# License: BSD-2-Clause

[service]
attribution = "Rapid7 Recog"
name = "smtp"
default_ports = []
description = "Imported from Rapid7 smtp_turn"

[[match]]
name = "\n         502 Hey!  I don't let remote systems TURN on me.\n      "
pattern = "^502[ -]Hey!  I don't let remote systems TURN on me\\.$"
vendor = "Alt-N"
product = "MDaemon"
context = "unknown"
metadata = { "service.family" = "MDaemon", "service.cpe23" = "cpe:/a:altn:mdaemon:-", "os.vendor" = "Microsoft", "os.family" = "Windows", "os.product" = "Windows", "os.arch" = "x86", "os.cpe23" = "cpe:/o:microsoft:windows:-" }

