# This file contains fingerprints imported from Rapid7 Recog.
# Source: https://github.com/rapid7/recog
# License: BSD-2-Clause

[service]
attribution = "Rapid7 Recog"
name = "architecture.xml"
default_ports = []
description = "Imported from Rapid7 architecture"

[[match]]
name = "x64 (x86_x64)"
pattern = "x64|amd64|x86_64"
context = "architecture"
example = "Linux claw 3.11.0-15-generic #23-Ubuntu SMP Mon Dec 9 18:17:04 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux"
metadata = { "os.arch" = "x86_64" }

[[match]]
name = "x86"
pattern = "x86|i[3456]86"
context = "architecture"
example = "Linux bob 3.2.0-1-generic #3-Ubuntu SMP Wed Dec 11 19:12:55 UTC 2013 i686 i686 i686 GNU/Linux"
metadata = { "os.arch" = "x86" }

[[match]]
name = "PowerPC"
pattern = "PowerPC|PPC|POWER"
context = "architecture"
example = "PowerPC"
metadata = { "os.arch" = "PowerPC" }

[[match]]
name = "SPARC"
pattern = "SPARC"
context = "architecture"
example = "SPARC"
metadata = { "os.arch" = "Sparc" }

[[match]]
name = "MIPS"
pattern = "mips"
context = "architecture"
example = "MIPS"
metadata = { "os.arch" = "MIPS" }

[[match]]
name = "ARM64 (aarch64)"
pattern = "arm64|aarch64"
context = "architecture"
example = "arm64"
metadata = { "os.arch" = "ARM64" }

[[match]]
name = "ARM"
pattern = "arm"
context = "architecture"
example = "arm"
metadata = { "os.arch" = "ARM" }

