[service]
name = "mysql"
default_ports = [3306]
description = "MySQL Database"

# MySQL sends a handshake on connect.
[[match]]
name = "mysql_handshake"
pattern = '^.[\x00\x00\x00]([\d.]+)'
version_group = 1
product = "mysql"
