[service]
name = "mysql"
default_ports = [3306]
description = "MySQL Database"

# MySQL sends a handshake on connect.
[[match]]
name = "mysql_handshake"
pattern = '(?s)^.{3}\x00\x0a([\w.\-+~]+)'
version_group = 1
product = "mysql"
