[service]
name = "riak"
default_ports = [8087, 8098]
description = "Riak KV"

[[probe]]
name = "pbc_ping"
payload = '\x00\x00\x00\x01\x01'
protocol = "tcp"

[[match]]
name = "pbc_pong"
pattern = '^\x00\x00\x00\x01\x02'
product = "riak_pbc"
