// Copyright (c) 2026 Erik Lening (hollowpointer) and Contributors
//
// This file is part of Zond Engine, licensed under the GNU Affero General
// Public License, version 3 or later. See the LICENSE file for details, or
// <https://www.gnu.org/licenses/agpl-3.0.html>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! # The National Vulnerability Database feed
//!
//! Turns a year of NVD's JSON into a [`Catalogue`] the correlator can use, as
//! [`kev`](super::kev) does for CISA's feed. What NVD adds is versions: a KEV
//! entry names a vendor and a product, and an NVD record carries the CPE ranges a
//! vulnerability applies to. That is the difference between *this host runs Exim,
//! go and look* and *this host runs Exim 4.90, which is in the affected range*.
//!
//! ```no_run
//! use std::fs::File;
//! use std::io::BufReader;
//!
//! let file = File::open("CVE-2024.json")?;
//! let catalogue = zond_engine::import::nvd::read(&mut BufReader::new(file))?;
//! # Ok::<(), Box<dyn std::error::Error>>(())
//! ```
//!
//! ## Where the bytes come from
//!
//! NVD retired its JSON feeds at the end of 2023 for a rate-limited REST API, so
//! this reads the shape the community reconstruction publishes: an object
//! carrying a `timestamp` and a `cve_items` array. The 2.0 API returns the same
//! records a page at a time, and pages assembled into that shape read unchanged.
//!
//! The catalogue this crate ships, `assets/cve/nvd.toml`, is this module's output
//! over every year of that feed, regenerated by the `nvd_catalogue` example.
//!
//! ## Filtering by the corpus
//!
//! A converted KEV holds every entry CISA published, about twelve hundred. NVD is
//! three hundred and eighty thousand records naming several hundred thousand
//! products, and converting all of it would exceed [`MAX_DOCUMENT_BYTES`] by two
//! orders of magnitude.
//!
//! [`SignatureDb::versioned_products`] is every `vendor:product` a scan can name
//! *with a version*, and a record naming anything else is dropped as it is read.
//! An entry for software the fingerprint corpus cannot version has nothing to
//! match against, in the sense of
//! [`Reach::Unproduced`](crate::fingerprint::Reach), so nothing findable is lost.
//! Two hundred and sixty-nine products are named by some rule but never with a
//! version; keeping their entries would add a megabyte that cannot fire.
//!
//! ## Applications only
//!
//! An `o:` CPE's version is a release family (`microsoft:windows_server_2016`,
//! `linux:linux_kernel`), and a scan cannot read a kernel's patch level off the
//! wire. An entry keyed there fires on every host of that family and can be
//! neither confirmed nor denied. `linux:linux_kernel` alone accounts for eighteen
//! thousand CPE matches in one year of the feed. KEV already makes the
//! product-level claim at
//! [`Confidence::Weak`](crate::model::confidence::Confidence::Weak), so this
//! reader keeps `a:` records and skips `o:`.
//!
//! ## Streaming
//!
//! A year of NVD is about three hundred megabytes, so the array is walked element
//! by element and each record is converted and dropped before the next is read.
//! Peak memory is one record plus whatever survived the filter.
//!
//! ## One record, several entries
//!
//! The catalogue's `affected` grammar is a comma-joined *conjunction*: every
//! clause must hold. Disjoint ranges are common (CVE-2024-6387 affects OpenSSH
//! below 4.4 *and* from 8.5 to 9.8), so each range becomes its own entry under the
//! same CVE id, and each product a record names gets its own entries.
//!
//! ## Platform conditions are dropped
//!
//! NVD writes *vulnerable only when running on X* as a configuration whose nodes
//! are joined by `AND`: the vulnerable application in one, and the platform,
//! marked not vulnerable, in another. Apache HTTP Server's Windows-only flaws,
//! distribution patches to OpenSSH and vendor appliance builds are written this
//! way. A catalogue entry is judged against one service's CPE alone, so the
//! condition cannot be expressed, and the entry would charge every host running
//! the product with a flaw that exists on one platform.
//!
//! Such a configuration converts to nothing; a range the same record also states
//! unconditionally is kept. About one and a half percent of the entries the
//! shipped corpus admits come only from conditional configurations. The platforms
//! named are operating systems in three cases out of four, then hardware, then the
//! odd application (a Windows or Red Hat build, an F5 or SonicWall appliance), and
//! the platform's own advisories are the better source for those.

use std::collections::BTreeSet;
use std::fmt;
use std::io::BufRead;

use serde::de::{DeserializeSeed, IgnoredAny, MapAccess, SeqAccess, Visitor};
use serde::{Deserialize, Deserializer, Serialize};

use crate::cve::{Catalogue, CatalogueError, MAX_DOCUMENT_BYTES};
use crate::fingerprint::SignatureDb;

/// The id a converted catalogue carries.
///
/// The `zond:` namespace is reserved for what this crate ships and is refused on
/// anything read from outside, so a report traces a finding back to NVD.
pub const NVD_ID: &str = "nvd:cve";

/// The most of a feed this will read.
///
/// A hundred times [`MAX_DOCUMENT_BYTES`]: a year of NVD is three hundred
/// megabytes and converts to a few hundred kilobytes. The cap stops an endless
/// source; the input is streamed, so it is never held whole.
pub const MAX_FEED_BYTES: u64 = 100 * MAX_DOCUMENT_BYTES;

/// The longest `title` an entry carries.
///
/// A title is the description's first sentence, cut here if still long. Titles
/// are just under half of a converted document's bytes.
const MAX_TITLE_BYTES: usize = 160;

/// Why an NVD feed could not be converted.
#[non_exhaustive]
#[derive(Debug, thiserror::Error)]
pub enum NvdError {
    /// The bytes could not be read.
    #[error("the NVD feed could not be read: {0}")]
    Io(#[from] std::io::Error),

    /// The document is not the JSON this feed publishes.
    #[error("the NVD feed is malformed: {0}")]
    Malformed(String),

    /// The feed was longer than [`MAX_FEED_BYTES`].
    #[error("the NVD feed is longer than the {limit} byte limit")]
    TooLarge {
        /// The limit it passed.
        limit: u64,
    },

    /// More of the feed survived the filter than a catalogue document may hold.
    ///
    /// The feed itself was fine; the result is too large to read back. Convert
    /// one year at a time.
    #[error("{entries} entries convert to more than the {limit} byte document limit")]
    TooManyEntries {
        /// How many entries were kept.
        entries: usize,
        /// The document limit they did not fit in.
        limit: u64,
    },

    /// The catalogue reader refused the converted document, which is a defect in
    /// the conversion.
    #[error("the converted catalogue was refused: {0}")]
    Rejected(#[from] CatalogueError),
}

/// Converts the NVD JSON in `input` into the TOML document
/// [`Catalogue::read`] consumes.
///
/// The result carries the id [`NVD_ID`] and the feed's `timestamp` as its
/// version, so reports from two dumps of the feed are told apart.
///
/// Filtered against the shipped fingerprint corpus; see the module documentation.
///
/// # Errors
///
/// [`NvdError::Malformed`] for JSON that is not this feed,
/// [`NvdError::TooLarge`] past [`MAX_FEED_BYTES`], and
/// [`NvdError::TooManyEntries`] where what survived the filter will not fit in a
/// catalogue document.
pub fn to_document(input: &mut dyn BufRead) -> Result<String, NvdError> {
    to_document_for(input, SignatureDb::global().versioned_products())
}

/// [`to_document`], filtered against the given `vendor:product` keys.
///
/// For a caller who fingerprints with a corpus of their own, and for tests that
/// need a filter independent of the shipped corpus.
///
/// # Errors
///
/// The same as [`to_document`].
pub fn to_document_for(
    input: &mut dyn BufRead,
    products: &BTreeSet<String>,
) -> Result<String, NvdError> {
    // One byte past the cap, so the count can tell an oversized feed from one
    // that ends exactly at it.
    let bounded = std::io::Read::take(input, MAX_FEED_BYTES.saturating_add(1));
    let counted = Counting::new(bounded);
    let read = counted.read.clone();

    let mut deserializer = serde_json::Deserializer::from_reader(counted);
    let feed = Feed { products }
        .deserialize(&mut deserializer)
        .map_err(|error| NvdError::Malformed(error.to_string()))?;

    if read.get() > MAX_FEED_BYTES {
        return Err(NvdError::TooLarge {
            limit: MAX_FEED_BYTES,
        });
    }

    let document = Document {
        id: NVD_ID.to_string(),
        version: feed_version(&feed.timestamp),
        vulnerability: feed.vulnerability,
    };

    // Serialised so that quotes and backslashes in NVD's strings are escaped.
    let toml =
        toml::to_string(&document).map_err(|error| NvdError::Malformed(error.to_string()))?;

    if toml.len() as u64 > MAX_DOCUMENT_BYTES {
        return Err(NvdError::TooManyEntries {
            entries: document.vulnerability.len(),
            limit: MAX_DOCUMENT_BYTES,
        });
    }
    Ok(toml)
}

/// Reads the NVD JSON in `input` as a [`Catalogue`].
///
/// [`to_document`] followed by [`Catalogue::read`]. When scans are re-run against
/// the same feed, convert once with [`to_document`] and keep the result: the
/// conversion reads several hundred megabytes and produces a few hundred
/// kilobytes.
///
/// # Errors
///
/// Everything [`to_document`] returns, and [`NvdError::Rejected`] where the
/// document it produced was refused.
pub fn read(input: &mut dyn BufRead) -> Result<Catalogue, NvdError> {
    let document = to_document(input)?;
    Ok(Catalogue::read(&mut document.as_bytes())?)
}

/// The feed's `timestamp` as the catalogue grammar's `major.minor.patch`.
///
/// `2026-09-08T00:00:09+00:00` becomes `2026.9.8`. Anything unparseable becomes
/// `0.0.0`, which sorts below every real version.
fn feed_version(timestamp: &str) -> String {
    let date = timestamp.split('T').next().unwrap_or_default();
    let mut parts = date.split('-');

    let mut number = || -> Option<u32> { parts.next()?.parse().ok() };
    match (number(), number(), number()) {
        (Some(year), Some(month), Some(day)) => format!("{year}.{month}.{day}"),
        _ => "0.0.0".to_string(),
    }
}

/// A reader that remembers how much went through it.
///
/// `Read::take` stops at the limit without saying whether it was reached. The
/// count lets a feed cut off at the cap be reported as too large and not as
/// malformed JSON.
struct Counting<R> {
    inner: R,
    read: std::rc::Rc<std::cell::Cell<u64>>,
}

impl<R> Counting<R> {
    fn new(inner: R) -> Self {
        Self {
            inner,
            read: std::rc::Rc::new(std::cell::Cell::new(0)),
        }
    }
}

impl<R: std::io::Read> std::io::Read for Counting<R> {
    fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
        let n = self.inner.read(buf)?;
        self.read.set(self.read.get().saturating_add(n as u64));
        Ok(n)
    }
}

/// The whole feed, deserialized against a filter.
///
/// A `DeserializeSeed` so the filter is applied while the array is walked, which
/// keeps only surviving records in memory.
struct Feed<'a> {
    products: &'a BTreeSet<String>,
}

/// The feed's timestamp and the entries that survived the filter.
struct Converted {
    timestamp: String,
    vulnerability: Vec<Entry>,
}

impl<'de> DeserializeSeed<'de> for Feed<'_> {
    type Value = Converted;

    fn deserialize<D: Deserializer<'de>>(self, deserializer: D) -> Result<Converted, D::Error> {
        deserializer.deserialize_map(self)
    }
}

impl<'de> Visitor<'de> for Feed<'_> {
    type Value = Converted;

    fn expecting(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("an NVD feed object carrying `cve_items`")
    }

    fn visit_map<A: MapAccess<'de>>(self, mut map: A) -> Result<Converted, A::Error> {
        let mut timestamp = String::new();
        let mut vulnerability = Vec::new();
        let mut seen_items = false;

        while let Some(key) = map.next_key::<String>()? {
            match key.as_str() {
                "timestamp" => timestamp = map.next_value()?,
                "cve_items" | "vulnerabilities" => {
                    seen_items = true;
                    vulnerability = map.next_value_seed(Records {
                        products: self.products,
                    })?;
                }
                // Unknown keys are skipped: the feed grows fields.
                _ => {
                    map.next_value::<IgnoredAny>()?;
                }
            }
        }

        if !seen_items {
            return Err(serde::de::Error::missing_field("cve_items"));
        }
        Ok(Converted {
            timestamp,
            vulnerability,
        })
    }
}

/// The `cve_items` array, converted as it is walked.
struct Records<'a> {
    products: &'a BTreeSet<String>,
}

impl<'de> DeserializeSeed<'de> for Records<'_> {
    type Value = Vec<Entry>;

    fn deserialize<D: Deserializer<'de>>(self, deserializer: D) -> Result<Vec<Entry>, D::Error> {
        deserializer.deserialize_seq(self)
    }
}

impl<'de> Visitor<'de> for Records<'_> {
    type Value = Vec<Entry>;

    fn expecting(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("an array of NVD records")
    }

    fn visit_seq<A: SeqAccess<'de>>(self, mut seq: A) -> Result<Vec<Entry>, A::Error> {
        let mut out = Vec::new();
        // One record in memory at a time, dropped once converted.
        while let Some(record) = seq.next_element::<Record>()? {
            entries_from(&record, self.products, &mut out);
        }
        Ok(out)
    }
}

/// One NVD record, cut down to what a catalogue entry needs.
///
/// The 2.0 API nests the record under a `cve` key and the reconstructed feed
/// does not; this type reads both. Every field defaults, because a record may
/// carry none of them: [`entries_from`] skips the ones it cannot convert.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Record {
    /// The nested record of the 2.0 API's shape, absent in the feed's.
    cve: Option<Box<Record>>,
    #[serde(default)]
    id: String,
    #[serde(default)]
    vuln_status: String,
    #[serde(default)]
    descriptions: Vec<Description>,
    #[serde(default)]
    metrics: Metrics,
    #[serde(default)]
    weaknesses: Vec<Weakness>,
    #[serde(default)]
    configurations: Vec<Configuration>,
}

/// A string in one language, used for both a CVE's summary and a weakness's text.
/// The feed ships several languages and only English is read.
#[derive(Deserialize)]
struct Description {
    lang: String,
    value: String,
}

/// The CVSS scores a record carries, newest version first.
#[derive(Default, Deserialize)]
#[serde(rename_all = "camelCase")]
struct Metrics {
    #[serde(default)]
    cvss_metric_v31: Vec<Metric>,
    #[serde(default)]
    cvss_metric_v30: Vec<Metric>,
    #[serde(default)]
    cvss_metric_v2: Vec<Metric>,
}

/// One score.
///
/// `base_severity` appears in two places: CVSS 3.x puts it inside `cvssData`
/// beside the score, and CVSS 2, whose specification has no such field, has
/// NVD's own on the metric. Reading only the 3.x position would drop every record
/// scored under version 2 alone.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Metric {
    #[serde(default)]
    base_severity: Option<String>,
    #[serde(default)]
    cvss_data: CvssData,
}

/// The `cvssData` object of a metric, holding the severity under CVSS 3.x. See
/// [`Metric`].
#[derive(Default, Deserialize)]
#[serde(rename_all = "camelCase")]
struct CvssData {
    #[serde(default)]
    base_severity: Option<String>,
}

/// A weakness the record cites. Its CWE identifier is the text of its
/// [`Description`].
#[derive(Deserialize)]
struct Weakness {
    #[serde(default)]
    description: Vec<Description>,
}

/// One configuration: the [`Node`]s naming the products and versions a record
/// applies to.
#[derive(Deserialize)]
struct Configuration {
    /// How the nodes combine: `AND` where every one must hold, and absent or
    /// `OR` where any one is enough.
    #[serde(default)]
    operator: Option<String>,
    #[serde(default)]
    nodes: Vec<Node>,
}

impl Configuration {
    /// Whether this configuration makes its vulnerable matches conditional on a
    /// platform: nodes joined by `AND`, one of which names nothing vulnerable.
    ///
    /// That node is the condition (*running on* an operating system, a device or
    /// another application). See the module documentation.
    fn is_platform_conditional(&self) -> bool {
        self.operator
            .as_deref()
            .is_some_and(|operator| operator.eq_ignore_ascii_case("and"))
            && self.nodes.iter().any(|node| {
                !node.cpe_match.is_empty()
                    && node.cpe_match.iter().all(|matched| !matched.vulnerable)
            })
    }
}

/// One node of a [`Configuration`], holding its CPE matches.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Node {
    #[serde(default)]
    cpe_match: Vec<CpeMatch>,
}

/// One CPE the record says is affected, with the range it is affected over.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct CpeMatch {
    #[serde(default = "yes")]
    vulnerable: bool,
    #[serde(default)]
    criteria: String,
    version_start_including: Option<String>,
    version_start_excluding: Option<String>,
    version_end_including: Option<String>,
    version_end_excluding: Option<String>,
}

/// The serde default for [`CpeMatch::vulnerable`], which the feed omits when the
/// match is vulnerable and states only to say it is not.
fn yes() -> bool {
    true
}

/// The catalogue document, as [`Catalogue::read`] expects it.
#[derive(Serialize)]
struct Document {
    id: String,
    version: String,
    vulnerability: Vec<Entry>,
}

/// One catalogue entry.
#[derive(Serialize)]
struct Entry {
    cve: String,
    title: String,
    severity: String,
    vendor: String,
    product: String,
    affected: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    cwe: Option<u32>,
}

/// Converts one record into however many entries it yields, appending them.
///
/// Most records yield none: they name no product this corpus can version, carry
/// no severity, or are withdrawn.
fn entries_from(record: &Record, products: &BTreeSet<String>, out: &mut Vec<Entry>) {
    let record = record.cve.as_deref().unwrap_or(record);

    // A rejected CVE was withdrawn, but its ranges stay in the record.
    if record.vuln_status.eq_ignore_ascii_case("rejected") {
        return;
    }
    let (Some(severity), Some(title)) = (severity_of(record), title_of(record)) else {
        return;
    };
    let cwe = cwe_of(record);

    // NVD often repeats a range across configurations; a duplicate entry would
    // be reported twice.
    let mut seen = BTreeSet::new();
    for configuration in &record.configurations {
        if configuration.is_platform_conditional() {
            continue;
        }
        for node in &configuration.nodes {
            for matched in &node.cpe_match {
                let Some((vendor, product, affected)) = affected_range(matched, products) else {
                    continue;
                };
                if !seen.insert((vendor.clone(), product.clone(), affected.clone())) {
                    continue;
                }
                out.push(Entry {
                    cve: record.id.clone(),
                    title: title.clone(),
                    severity: severity.clone(),
                    vendor,
                    product,
                    affected,
                    cwe,
                });
            }
        }
    }
}

/// The `vendor`, `product` and `affected` clause one CPE match yields, where it
/// names something this corpus can version.
///
/// [`None`] for a CPE naming something else, one marked not vulnerable (it says
/// what must be *present* for the flaw), and one stating neither a range nor a
/// version.
fn affected_range(
    matched: &CpeMatch,
    products: &BTreeSet<String>,
) -> Option<(String, String, String)> {
    if !matched.vulnerable {
        return None;
    }

    // `cpe:2.3:a:vendor:product:version:...`, `a:` only. Split and unescaped as
    // the correlator reads a service's, so `7.03hp3\+ftf` names the release a
    // banner states.
    let fields = crate::cve::formatted_fields(matched.criteria.strip_prefix("cpe:2.3:")?);
    let mut parts = fields.iter().map(String::as_str);
    if parts.next()? != "a" {
        return None;
    }
    let vendor = parts.next()?;
    let product = parts.next()?;
    let version = parts.next()?;
    let update = parts.next().unwrap_or_default();

    let key = format!("{vendor}:{product}");
    if !products.contains(&key) {
        return None;
    }

    let clauses: Vec<String> = [
        (">=", &matched.version_start_including),
        (">", &matched.version_start_excluding),
        ("<=", &matched.version_end_including),
        ("<", &matched.version_end_excluding),
    ]
    .iter()
    .filter_map(|(op, bound)| {
        bound
            .as_ref()
            .map(|value| format!("{op} {}", unescaped(value)))
    })
    .collect();

    let affected = match clauses.is_empty() {
        // No range, so the CPE's version field is the claim. A wildcard there
        // means every release, which KEV's product-level entries cover.
        true if is_unset(version) => return None,
        // The 2.3 grammar puts a patch level in its own field, `6.6:p1`, where
        // banners and the URI form write `6.6p1`. Joined as the correlator joins
        // a service's CPE: `== 6.6` alone matches no OpenSSH ever shipped.
        true if is_unset(update) => format!("== {version}"),
        true => format!("== {version}{update}"),
        // The grammar has no clause for an update field beside a range (NVD
        // writes one rarely and inconsistently), so it is dropped, which can
        // only broaden the claim.
        false => clauses.join(", "),
    };
    Some((vendor.to_string(), product.to_string(), affected))
}

/// A value NVD wrote with the 2.3 grammar's escapes, unescaped. See
/// [`formatted_fields`](crate::cve::formatted_fields).
fn unescaped(value: &str) -> String {
    let mut plain = String::with_capacity(value.len());
    let mut characters = value.chars();
    while let Some(character) = characters.next() {
        match character {
            '\\' => plain.extend(characters.next()),
            other => plain.push(other),
        }
    }
    plain
}

/// Whether a CPE field states nothing: `*` is "any" and `-` is "not
/// applicable" in the 2.3 grammar, and an empty field is absent.
fn is_unset(field: &str) -> bool {
    matches!(field, "*" | "-" | "")
}

/// The severity a record carries, lowercased, from its newest scoring.
///
/// CVSS 3.1 over 3.0 over 2, as NVD shows it. [`None`] for a record
/// with no score, which is every record still awaiting analysis.
fn severity_of(record: &Record) -> Option<String> {
    [
        &record.metrics.cvss_metric_v31,
        &record.metrics.cvss_metric_v30,
        &record.metrics.cvss_metric_v2,
    ]
    .into_iter()
    .flatten()
    .find_map(|metric| {
        metric
            .cvss_data
            .base_severity
            .as_deref()
            .or(metric.base_severity.as_deref())
    })
    .map(str::to_ascii_lowercase)
}

/// The first sentence of the English description, as the entry's title, cut at
/// [`MAX_TITLE_BYTES`] and without its trailing full stop.
///
/// The first sentence almost always states what the vulnerability is; the rest
/// gives conditions.
fn title_of(record: &Record) -> Option<String> {
    let english = record
        .descriptions
        .iter()
        .find(|description| description.lang == "en")?;

    let mut title = String::with_capacity(MAX_TITLE_BYTES);
    let mut whitespace = false;
    for character in english.value.trim().chars() {
        if character.is_whitespace() {
            whitespace = !title.is_empty();
            continue;
        }
        if whitespace {
            // A sentence ends at `.`, `!` or `?` followed by whitespace, which
            // skips the dots inside `4.9.1`.
            if title.ends_with('.') || title.ends_with('!') || title.ends_with('?') {
                break;
            }
            title.push(' ');
            whitespace = false;
        }
        if title.len() + character.len_utf8() > MAX_TITLE_BYTES {
            break;
        }
        title.push(character);
    }

    let title = title.trim_end_matches(['.', ' ']).to_string();
    (!title.is_empty()).then_some(title)
}

/// The CWE a record names, where it names one as a number.
///
/// NVD also writes non-answers here (`NVD-CWE-noinfo`, `NVD-CWE-Other`,
/// `Unsure`), which are skipped. The first `CWE-` number wins; [`None`] if there
/// is none.
fn cwe_of(record: &Record) -> Option<u32> {
    record
        .weaknesses
        .iter()
        .flat_map(|weakness| weakness.description.iter())
        .filter(|description| description.lang == "en")
        .find_map(|description| description.value.strip_prefix("CWE-")?.parse().ok())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn products(names: &[&str]) -> BTreeSet<String> {
        names.iter().map(|name| (*name).to_string()).collect()
    }

    /// One record in the reconstructed feed's shape, carrying the exim range the
    /// shipped seed states by hand.
    const EXIM: &str = r#"{
      "timestamp": "2026-09-08T00:00:09+00:00",
      "cve_count": 1,
      "cve_items": [{
        "id": "CVE-2019-10149",
        "vulnStatus": "Analyzed",
        "descriptions": [
          {"lang": "es", "value": "Se descubrio un fallo."},
          {"lang": "en", "value": "A flaw was found in Exim 4.87 to 4.91. Improper validation of recipient address."}
        ],
        "metrics": {"cvssMetricV31": [{"cvssData": {"baseSeverity": "CRITICAL"}}]},
        "weaknesses": [{"description": [{"lang": "en", "value": "CWE-78"}]}],
        "configurations": [{"nodes": [{"cpeMatch": [
          {"vulnerable": true, "criteria": "cpe:2.3:a:exim:exim:*:*:*:*:*:*:*:*",
           "versionStartIncluding": "4.87", "versionEndIncluding": "4.91"},
          {"vulnerable": true, "criteria": "cpe:2.3:o:debian:debian_linux:9.0:*:*:*:*:*:*:*"}
        ]}]}]
      }]
    }"#;

    /// The conversion reproduces the exim entry written by hand from the advisory
    /// into `assets/cve/seed.toml`: `>= 4.87, <= 4.91`.
    #[test]
    fn a_record_converts_to_the_entry_a_person_wrote_by_hand() {
        let document = to_document_for(&mut EXIM.as_bytes(), &products(&["exim:exim"]))
            .expect("the feed converts");

        assert!(document.contains(r#"cve = "CVE-2019-10149""#), "{document}");
        assert!(
            document.contains(r#"affected = ">= 4.87, <= 4.91""#),
            "{document}"
        );
        assert!(document.contains(r#"severity = "critical""#), "{document}");
        assert!(document.contains(r#"vendor = "exim""#), "{document}");
        assert!(document.contains(r#"product = "exim""#), "{document}");
        assert!(document.contains("cwe = 78"), "{document}");

        // The first sentence of the English description.
        assert!(
            document.contains(r#"title = "A flaw was found in Exim 4.87 to 4.91""#),
            "{document}"
        );
    }

    /// The operating system named in the same record is skipped. The Debian 9
    /// CPE says which distribution shipped the flawed exim.
    #[test]
    fn an_operating_system_cpe_is_left_alone() {
        let document = to_document_for(
            &mut EXIM.as_bytes(),
            &products(&["exim:exim", "debian:debian_linux"]),
        )
        .expect("the feed converts");

        assert!(!document.contains("debian"), "{document}");
        assert_eq!(document.matches("[[vulnerability]]").count(), 1);
    }

    /// A product the corpus cannot name with a version is dropped.
    #[test]
    fn a_product_the_corpus_cannot_version_is_dropped() {
        let document = to_document_for(&mut EXIM.as_bytes(), &products(&["nothing:at_all"]))
            .expect("converts");

        assert_eq!(
            document.matches("[[vulnerability]]").count(),
            0,
            "{document}"
        );
        // An empty result is still a named, dated catalogue.
        assert!(document.contains(r#"id = "nvd:cve""#), "{document}");
        assert!(document.contains(r#"version = "2026.9.8""#), "{document}");
    }

    /// Disjoint ranges become one entry each, because `affected` is a
    /// conjunction and cannot say "or".
    #[test]
    fn disjoint_ranges_become_separate_entries() {
        const REGRESSHION: &str = r#"{
          "timestamp": "2026-09-08T00:00:00+00:00",
          "cve_items": [{
            "id": "CVE-2024-6387",
            "descriptions": [{"lang": "en", "value": "A signal handler race condition in OpenSSH."}],
            "metrics": {"cvssMetricV31": [{"cvssData": {"baseSeverity": "HIGH"}}]},
            "configurations": [{"nodes": [{"cpeMatch": [
              {"vulnerable": true, "criteria": "cpe:2.3:a:openbsd:openssh:*:*:*:*:*:*:*:*",
               "versionEndExcluding": "4.4"},
              {"vulnerable": true, "criteria": "cpe:2.3:a:openbsd:openssh:*:*:*:*:*:*:*:*",
               "versionStartIncluding": "8.5", "versionEndExcluding": "9.8"}
            ]}]}]
          }]
        }"#;

        let document =
            to_document_for(&mut REGRESSHION.as_bytes(), &products(&["openbsd:openssh"]))
                .expect("converts");

        assert_eq!(
            document.matches("[[vulnerability]]").count(),
            2,
            "{document}"
        );
        assert!(document.contains(r#"affected = "< 4.4""#), "{document}");
        assert!(
            document.contains(r#"affected = ">= 8.5, < 9.8""#),
            "{document}"
        );
    }

    /// The same range stated in two configurations is one entry.
    #[test]
    fn a_repeated_range_is_recorded_once() {
        const REPEATED: &str = r#"{
          "timestamp": "2026-01-02T00:00:00+00:00",
          "cve_items": [{
            "id": "CVE-2024-0001",
            "descriptions": [{"lang": "en", "value": "Something in Tomcat."}],
            "metrics": {"cvssMetricV31": [{"cvssData": {"baseSeverity": "MEDIUM"}}]},
            "configurations": [
              {"nodes": [{"cpeMatch": [{"vulnerable": true,
                "criteria": "cpe:2.3:a:apache:tomcat:9.0.1:*:*:*:*:*:*:*"}]}]},
              {"nodes": [{"cpeMatch": [{"vulnerable": true,
                "criteria": "cpe:2.3:a:apache:tomcat:9.0.1:*:*:*:*:*:*:*"}]}]}
            ]
          }]
        }"#;

        let document = to_document_for(&mut REPEATED.as_bytes(), &products(&["apache:tomcat"]))
            .expect("converts");

        assert_eq!(
            document.matches("[[vulnerability]]").count(),
            1,
            "{document}"
        );
        assert!(document.contains(r#"affected = "== 9.0.1""#), "{document}");
    }

    /// A CVSS 2 record is scored from the severity on the metric itself.
    #[test]
    fn a_cvss_2_record_is_still_scored() {
        const OLD: &str = r#"{
          "timestamp": "2026-01-02T00:00:00+00:00",
          "cve_items": [{
            "id": "CVE-2009-0001",
            "descriptions": [{"lang": "en", "value": "An old flaw in ProFTPD."}],
            "metrics": {"cvssMetricV2": [{"baseSeverity": "HIGH", "cvssData": {"baseScore": 7.5}}]},
            "configurations": [{"nodes": [{"cpeMatch": [{"vulnerable": true,
              "criteria": "cpe:2.3:a:proftpd:proftpd:1.3.1:*:*:*:*:*:*:*"}]}]}]
          }]
        }"#;

        let document = to_document_for(&mut OLD.as_bytes(), &products(&["proftpd:proftpd"]))
            .expect("converts");
        assert!(document.contains(r#"severity = "high""#), "{document}");
    }

    /// Records with nothing to convert yield no entry: a withdrawn CVE, an
    /// unscored one, a CPE marked as a precondition, and a wildcard version.
    #[test]
    fn a_record_with_nothing_to_say_yields_nothing() {
        const NOTHING: &str = r#"{
          "timestamp": "2026-01-02T00:00:00+00:00",
          "cve_items": [
            {"id": "CVE-2024-1", "vulnStatus": "Rejected",
             "descriptions": [{"lang": "en", "value": "Withdrawn."}],
             "metrics": {"cvssMetricV31": [{"cvssData": {"baseSeverity": "HIGH"}}]},
             "configurations": [{"nodes": [{"cpeMatch": [{"vulnerable": true,
               "criteria": "cpe:2.3:a:apache:tomcat:9.0.1:*:*:*:*:*:*:*"}]}]}]},
            {"id": "CVE-2024-2",
             "descriptions": [{"lang": "en", "value": "Not yet scored."}],
             "configurations": [{"nodes": [{"cpeMatch": [{"vulnerable": true,
               "criteria": "cpe:2.3:a:apache:tomcat:9.0.2:*:*:*:*:*:*:*"}]}]}]},
            {"id": "CVE-2024-3",
             "descriptions": [{"lang": "en", "value": "Needs something present."}],
             "metrics": {"cvssMetricV31": [{"cvssData": {"baseSeverity": "HIGH"}}]},
             "configurations": [{"nodes": [{"cpeMatch": [
               {"vulnerable": false, "criteria": "cpe:2.3:a:apache:tomcat:9.0.3:*:*:*:*:*:*:*"},
               {"vulnerable": true, "criteria": "cpe:2.3:a:apache:tomcat:*:*:*:*:*:*:*:*"}
             ]}]}]}
          ]
        }"#;

        let document = to_document_for(&mut NOTHING.as_bytes(), &products(&["apache:tomcat"]))
            .expect("converts");
        assert_eq!(
            document.matches("[[vulnerability]]").count(),
            0,
            "{document}"
        );
    }

    /// The 2.0 API's shape, with the record nested under `cve`, is read too.
    #[test]
    fn the_api_shape_is_read_as_well_as_the_feed_shape() {
        const NESTED: &str = r#"{
          "timestamp": "2026-01-02T00:00:00+00:00",
          "vulnerabilities": [{"cve": {
            "id": "CVE-2024-0002",
            "descriptions": [{"lang": "en", "value": "Something in Tomcat."}],
            "metrics": {"cvssMetricV31": [{"cvssData": {"baseSeverity": "LOW"}}]},
            "configurations": [{"nodes": [{"cpeMatch": [{"vulnerable": true,
              "criteria": "cpe:2.3:a:apache:tomcat:10.1.0:*:*:*:*:*:*:*"}]}]}]
          }}]
        }"#;

        let document = to_document_for(&mut NESTED.as_bytes(), &products(&["apache:tomcat"]))
            .expect("converts");
        assert!(document.contains(r#"cve = "CVE-2024-0002""#), "{document}");
        assert!(document.contains(r#"affected = "== 10.1.0""#), "{document}");
    }

    /// End to end: a feed converts, reads back as a catalogue, and its range
    /// separates two hosts differing only in their exim version.
    ///
    /// `read` uses the shipped corpus, so this also checks that it admits exim.
    #[test]
    fn a_converted_range_tells_two_versions_apart() {
        use crate::model::host::Host;
        use crate::model::port::{Port, PortState, Protocol, Service};

        let catalogue = read(&mut EXIM.as_bytes()).expect("the feed reads as a catalogue");
        assert_eq!(catalogue.id(), NVD_ID);
        assert_eq!(catalogue.len(), 1);

        let matched = |version: &str| {
            let mut host = Host::new("192.0.2.1".parse().expect("an address"));
            let service = Service::new("smtp", 90).with_cpe(format!("cpe:/a:exim:exim:{version}"));
            host.add_port(Port::new(25, Protocol::Tcp, PortState::Open).with_service(service));
            crate::cve::correlate_with(&mut host, &catalogue);
            host.ports()
                .find(|port| port.number() == 25)
                .expect("the port")
                .findings()
                .any(|finding| finding.detection().id() == NVD_ID)
        };

        assert!(matched("4.90"), "4.90 is inside >= 4.87, <= 4.91");
        assert!(
            !matched("4.92"),
            "4.92 is past the range and must not match"
        );
    }

    /// A patch level NVD states in the CPE's `update` field is part of the
    /// release the entry names.
    ///
    /// NVD writes OpenSSH's `6.6:p1` where banners say `6.6p1`, and `== 6.6`
    /// would match no OpenSSH ever released. A service in either CPE spelling
    /// matches, and one at the release without the patch level does not. `-`
    /// and `*` add nothing.
    #[test]
    fn a_patch_level_in_the_update_field_is_part_of_the_version() {
        // A server-side flaw: the correlator withdraws client-side ones, which
        // would make the assertions below test that instead.
        const KEYBOARD_INTERACTIVE: &str = r#"{
          "timestamp": "2026-09-08T00:00:00+00:00",
          "cve_items": [{
            "id": "CVE-2015-5600",
            "descriptions": [{"lang": "en", "value": "keyboard-interactive devices allow unlimited retries."}],
            "metrics": {"cvssMetricV31": [{"cvssData": {"baseSeverity": "MEDIUM"}}]},
            "configurations": [{"nodes": [{"cpeMatch": [
              {"vulnerable": true, "criteria": "cpe:2.3:a:openbsd:openssh:6.6:p1:*:*:*:*:*:*"},
              {"vulnerable": true, "criteria": "cpe:2.3:a:openbsd:openssh:7.0:-:*:*:*:*:*:*"},
              {"vulnerable": true, "criteria": "cpe:2.3:a:openbsd:openssh:7.1:*:*:*:*:*:*:*"}
            ]}]}]
          }]
        }"#;

        let document = to_document_for(
            &mut KEYBOARD_INTERACTIVE.as_bytes(),
            &products(&["openbsd:openssh"]),
        )
        .expect("converts");
        assert!(document.contains(r#"affected = "== 6.6p1""#), "{document}");
        assert!(document.contains(r#"affected = "== 7.0""#), "{document}");
        assert!(document.contains(r#"affected = "== 7.1""#), "{document}");

        let catalogue = Catalogue::read(&mut document.as_bytes()).expect("reads back");
        let matched = |cpe: &str| {
            use crate::model::host::Host;
            use crate::model::port::{Port, PortState, Protocol, Service};

            let mut host = Host::new("192.0.2.1".parse().expect("an address"));
            let service = Service::new("ssh", 90).with_cpe(cpe);
            host.add_port(Port::new(22, Protocol::Tcp, PortState::Open).with_service(service));
            crate::cve::correlate_with(&mut host, &catalogue);
            host.ports()
                .find(|port| port.number() == 22)
                .expect("the port")
                .findings()
                .any(|finding| finding.detection().id() == NVD_ID)
        };

        assert!(matched("cpe:/a:openbsd:openssh:6.6p1"), "the URI form");
        assert!(
            matched("cpe:2.3:a:openbsd:openssh:6.6:p1:*:*:*:*:*:*"),
            "the 2.3 form"
        );
        assert!(
            !matched("cpe:/a:openbsd:openssh:6.6"),
            "a release without the patch level is not the one named"
        );
    }

    /// A configuration conditional on a platform converts to nothing, and an
    /// unconditional one beside it converts.
    ///
    /// CVE-2024-40898 is Windows-only, written as the vulnerable Apache and the
    /// non-vulnerable Windows joined by `AND`. CVE-2024-38476 states its range
    /// plainly.
    #[test]
    fn a_range_that_holds_only_on_a_platform_is_dropped() {
        const PLATFORM: &str = r#"{
          "timestamp": "2026-09-08T00:00:00+00:00",
          "cve_items": [
            {"id": "CVE-2024-40898",
             "descriptions": [{"lang": "en", "value": "SSRF in Apache HTTP Server on Windows."}],
             "metrics": {"cvssMetricV31": [{"cvssData": {"baseSeverity": "HIGH"}}]},
             "configurations": [{"operator": "AND", "nodes": [
               {"operator": "OR", "negate": false, "cpeMatch": [
                 {"vulnerable": true, "criteria": "cpe:2.3:a:apache:http_server:*:*:*:*:*:*:*:*",
                  "versionStartIncluding": "2.4.0", "versionEndExcluding": "2.4.62"}]},
               {"operator": "OR", "negate": false, "cpeMatch": [
                 {"vulnerable": false, "criteria": "cpe:2.3:o:microsoft:windows:-:*:*:*:*:*:*:*"}]}
             ]}]},
            {"id": "CVE-2024-38476",
             "descriptions": [{"lang": "en", "value": "Information disclosure in Apache HTTP Server."}],
             "metrics": {"cvssMetricV31": [{"cvssData": {"baseSeverity": "CRITICAL"}}]},
             "configurations": [{"nodes": [
               {"operator": "OR", "negate": false, "cpeMatch": [
                 {"vulnerable": true, "criteria": "cpe:2.3:a:apache:http_server:*:*:*:*:*:*:*:*",
                  "versionEndExcluding": "2.4.60"}]}
             ]}]}
          ]
        }"#;

        let document =
            to_document_for(&mut PLATFORM.as_bytes(), &products(&["apache:http_server"]))
                .expect("converts");

        assert!(!document.contains("CVE-2024-40898"), "{document}");
        assert!(document.contains(r#"cve = "CVE-2024-38476""#), "{document}");
        assert_eq!(
            document.matches("[[vulnerability]]").count(),
            1,
            "{document}"
        );
    }

    /// A range a record states both plainly and under a platform is kept from
    /// the plain statement.
    #[test]
    fn a_range_stated_plainly_as_well_survives_its_platform_twin() {
        const BOTH: &str = r#"{
          "timestamp": "2026-09-08T00:00:00+00:00",
          "cve_items": [{"id": "CVE-2024-0003",
             "descriptions": [{"lang": "en", "value": "Something in Tomcat."}],
             "metrics": {"cvssMetricV31": [{"cvssData": {"baseSeverity": "HIGH"}}]},
             "configurations": [
               {"operator": "AND", "nodes": [
                 {"cpeMatch": [{"vulnerable": true,
                   "criteria": "cpe:2.3:a:apache:tomcat:*:*:*:*:*:*:*:*", "versionEndExcluding": "9.0.2"}]},
                 {"cpeMatch": [{"vulnerable": false,
                   "criteria": "cpe:2.3:o:debian:debian_linux:10.0:*:*:*:*:*:*:*"}]}]},
               {"nodes": [{"cpeMatch": [{"vulnerable": true,
                 "criteria": "cpe:2.3:a:apache:tomcat:*:*:*:*:*:*:*:*", "versionEndExcluding": "9.0.2"}]}]}
             ]}]
        }"#;

        let document =
            to_document_for(&mut BOTH.as_bytes(), &products(&["apache:tomcat"])).expect("converts");
        assert_eq!(
            document.matches("[[vulnerability]]").count(),
            1,
            "{document}"
        );
        assert!(document.contains(r#"affected = "< 9.0.2""#), "{document}");
    }

    /// A feed without a parseable date takes version `0.0.0`.
    #[test]
    fn an_undated_feed_takes_a_version_that_says_so() {
        assert_eq!(feed_version("2026-09-08T00:00:09+00:00"), "2026.9.8");
        assert_eq!(feed_version("2024-01-02"), "2024.1.2");
        assert_eq!(feed_version(""), "0.0.0");
        assert_eq!(feed_version("last Tuesday"), "0.0.0");
    }

    /// A long single-sentence description is cut at the cap, and the dots in a
    /// version number do not end the sentence.
    #[test]
    fn a_title_is_a_sentence_and_never_longer_than_the_cap() {
        let record = Record {
            cve: None,
            id: String::new(),
            vuln_status: String::new(),
            descriptions: vec![Description {
                lang: "en".into(),
                value: format!("A flaw in version 1.2.3 of the thing {}", "x".repeat(400)),
            }],
            metrics: Metrics::default(),
            weaknesses: Vec::new(),
            configurations: Vec::new(),
        };

        let title = title_of(&record).expect("a title");
        assert!(title.len() <= MAX_TITLE_BYTES, "{}", title.len());
        assert!(
            title.starts_with("A flaw in version 1.2.3 of the thing"),
            "the dots in a version number do not end the sentence: {title}"
        );
    }
}
